import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs pathmgmt
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories mirror the shape shared across warehouse-systems
 * documentation sites: Overview, Domain-Driven Design, API Reference,
 * Ecosystem, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'ddd/ubiquitous-language',
    'ddd/aggregates-and-invariants',
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/rest/process-path-management-api'},
      items: [...apiSidebar],
    },
    'ecosystem/context-map',
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-process-path-management-bounded-context',
        'adr/0002-yaml-to-kafka-cutover',
        'adr/0003-transactional-outbox',
        'adr/0004-rest-auth-adoption',
        'adr/0005-remove-rest-auth',
        'adr/0006-mcp-server-second-inbound-adapter',
        'adr/0007-analytical-data-product',
      ],
    },
  ],
};

export default sidebars;
